sudo: required
dist: trusty

branches:
    except:
        - l10n_develop

language: cpp

cache:
    ccache: true
    directories:
        - $HOME/.cache/pip

os: linux

compiler:
    - gcc
    - clang

env:
    global:
        - PATH=$PATH:$PWD/install/bin
        - CLANG_VERSION="3.6"
    matrix:
        - RELEASE=
        - RELEASE=true

matrix:
    include:
        - os: osx
          compiler: clang
          env: RELEASE=true  # OS X builds are slow and limited.

addons:
    apt:
        packages:
            - gcc-4.9
            - g++-4.9
            - libxml2-dev
            - libgoogle-perftools-dev
            - qtbase5-dev
            - qtbase5-dev-tools
            - qttools5-dev
            - qttools5-dev-tools
            - libqt5svg5-dev
            - libqt5opengl5-dev
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - sourceline: "ppa:kzemek/boost"

before_install:
    - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] has been found, exiting."
      && exit 0 || echo "continue"

install:
    - .travis/install.sh  # Dependencies are built with gcc or clang.
    - if [[ "$CXX" == "clang++" ]] && [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
          export CC=clang-${CLANG_VERSION};
          export CXX=clang++-${CLANG_VERSION};
      fi

before_script:
    - .travis/before_script.sh

script:
    - .travis/script.sh
