language: cpp

compiler: gcc

before_install: sudo apt-get update -qq

install:
    - sudo apt-get install -qq libboost-all-dev
    - sudo apt-get install -qq libboost-random-dev
    - sudo apt-get install -qq python2.7
    - sudo pip install cpp-coveralls

script: ./install.py -p

after_success:
    - ./coveralls.sh
