sudo: required
dist: trusty

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

matrix:
    exclude:
        - os: osx
          compiler: gcc  # GCC is Clang on OS X.

env:
    global:
        - PATH=$PATH:`pwd`/install/bin
    matrix:
        - RELEASE=
        - RELEASE=true

addons:
    apt:
        packages:
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - libboost-system-dev
            - libboost-math-dev
            - libxml2-dev
            - libxml++2.6-dev
            - libgoogle-perftools-dev
            - qt5-default

install:
    - .travis/install.sh

before_script:
    - mkdir install

script:
    - .travis/script.sh
