language: cpp

compiler: gcc

env:
    - PATH=$PATH:`pwd`/build/bin

before_install: sudo apt-get update -qq

install:
    - sudo apt-get install -qq libboost-all-dev
    - sudo apt-get install -qq libboost-random-dev
    - sudo apt-get install -qq python2.7
    - sudo apt-get install -qq graphviz
    - sudo pip install cpp-coveralls
    - sudo pip install nose

script:
    - ./install.py -p
    - ./.run_tests.sh

after_success:
    - coveralls  --verbose  --exclude tests  --exclude ./build/CMakeFiles/
      --exclude ./build/lib/  --exclude src/error.h --exclude src/error.cc
      --exclude ./build/bin/  --exclude src/event.h
