sudo: required
dist: trusty

branches:
    except:
        - l10n_develop

language: cpp

cache:
    ccache: true
    directories:
        - $HOME/.cache/pip

os: linux

compiler:
    - gcc
    - clang

env:
    global:
        - PATH=$HOME/.local/bin:$PATH:$PWD/install/bin
        - QT_QPA_FONTDIR=/usr/share/fonts
        - QT_QPA_PLATFORM=offscreen
    matrix:
        - CONFIG=Debug
        - CONFIG=Release

jobs:
    include:
        - stage: lint
          dist: trusty
          sudo: false
          compiler: clang
          script: .travis/lint.sh
          env: CONFIG=Lint  # Travis does not provide ENV var for stage names :(
          addons:
              apt:
                  packages:
                      - qttools5-dev-tools
        - stage: test
          os: osx  # OS X builds are slow and limited.
          compiler: clang
          env: CONFIG=Release
        - stage: test
          compiler: gcc
          env: CONFIG=Coverage
    exclude:
        - compiler: gcc
          env: CONFIG=Debug

stages:
    - lint
    - test

addons:
    apt:
        packages:
            - gcc-4.9
            - g++-4.9
            - libxml2-dev
            - libgoogle-perftools-dev
            - qtbase5-dev
            - qtbase5-dev-tools
            - qttools5-dev
            - qttools5-dev-tools
            - libqt5svg5-dev
            - libqt5opengl5-dev
            - fontconfig
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:kzemek/boost"

before_install:
    - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] has been found, exiting."
      && exit 0 || echo "continue"
    - mkdir -p ~/.local/bin

install:
    - .travis/install.sh  # Dependencies are built with gcc or clang.

before_script:
    - .travis/before_script.sh

script:
    - .travis/script.sh
