language: cpp

compiler: gcc

env:
    - PATH=$PATH:`pwd`/install/bin

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
    - sudo add-apt-repository -y ppa:beineri/opt-qt521
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq gcc-4.8 g++-4.8
    - sudo apt-get install -qq ggcov
    - sudo apt-get install -qq libboost-program-options1.48-dev
    - sudo apt-get install -qq libboost-filesystem1.48-dev
    - sudo apt-get install -qq libboost-system1.48-dev
    - sudo apt-get install -qq libboost-math1.48-dev
    - sudo apt-get install -qq libxml2-dev
    - sudo apt-get install -qq libxml++2.6-dev
    - sudo apt-get install -qq libgoogle-perftools-dev
    - sudo apt-get install -qq python-lxml
    - sudo apt-get install -qq graphviz
    - sudo apt-get install -qq qt52base
    - sudo apt-get install -qq cmake
    - sudo pip install cpp-coveralls
    - sudo pip install nose

before_script:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
    - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.8 20
    - source /opt/qt52/bin/qt52-env.sh
    - mkdir ./install

script:
    - ./install.py -p --prefix=./install --threads 2 && ./.run_tests.sh

after_success:
    - coveralls --exclude tests  --exclude ./build/CMakeFiles/
      --exclude ./build/lib/ --exclude ./build/gui/
      --exclude ./build/bin/  --exclude install/include/
      --exclude gui/
      --exclude src/error.cc
      --exclude src/env.cc
      --exclude src/version.cc
      --exclude src/logger.cc
      --exclude-pattern .*/src/.*\.h$
      > /dev/null
