sudo: required
dist: trusty

language: cpp

cache: ccache

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    global:
        - PATH=$PATH:`pwd`/install/bin
        - CCACHE_CPP2=true
        # Intel Parallel Studio
        - secure: "BM1aLsCy0NYk1TCCMeQH6H1O9B+NmZeO6QzRTjy1Xrs8wvoKsuBiazjxSZ6nVWP3F+JtjsOLzeFyELmCf4lobcw8bhzgLZ7ZFaDJl4DC31w+87RdQFYzMe5t53SfflkfBDYkbpbUrt1B7qPk5r0nYDG+QzO3T/XnvSN/0HvmEBQ="
    matrix:
        - RELEASE=
        - RELEASE=true

matrix:
    exclude:
        - os: osx
          compiler: gcc  # GCC is Clang on OS X.
    include:
        - os: linux
          compiler: icc
          env: INTEL_COMPILER=true

addons:
    apt:
        packages:
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - libboost-system-dev
            - libboost-math-dev
            - libboost-date-time-dev
            - libxml2-dev
            - libxml++2.6-dev
            - libgoogle-perftools-dev
            - qt5-default

before_install:
    - if [[ -n "${INTEL_COMPILER}" ]]; then export CC=icc; export CXX=icpc; export RELEASE=true; fi

install:
    - .travis/install.sh

before_script:
    - mkdir install

script:
    - .travis/script.sh

after_script:
    - if [[ -n "${INTEL_COMPILER}" ]]; then ${HOME}/intel/parallel_studio*/uninstall.sh --silent; fi
