sudo: required

services:
    - docker

language: python

git:
    depth: 200

env:
    global:
        - secure: "UJW5Xm0VuDsEVcHWBv5njV4wadSKdsQ+gJkDINprKkAeOE1F7qxbzeQ7y9gou6SV59fcYbKLbVoXPPp1CFSZo36XNhIYOyEZXRbqWwl97JiDc47ymuNkhRMpnRqphpFVcTWDOhL9jIcixsF5Yus/YAgpv74RC9lPkFMpNXpJQoA="

before_install:
    - docker build -t scram/gh-pages .

script:
    - docker run scram/gh-pages
    - docker cp $(docker ps -alq):scram/build ./

deploy:
    local_dir: build/html
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: gh-source
