sudo: required
dist: trusty

language: cpp

compiler:
    - gcc
    - clang

git:
    depth: 3

env:
    global:
        - PATH=$PATH:`pwd`/install/bin
    matrix:
        - RELEASE=
        - RELEASE=true

addons:
    apt:
        packages:
            - libboost-program-options-dev
            - libboost-filesystem-dev
            - libboost-system-dev
            - libboost-math-dev
            - libxml2-dev
            - libxml++2.6-dev
            - libgoogle-perftools-dev
            - qt5-default
            - python-lxml
            - graphviz

before_install:
    - sudo apt-get update -qq

install:
    - ./.travis/install.sh

before_script:
    - mkdir ./install

script:
    - ./.travis/script.sh
