sudo: required
dist: trusty

branches:
    except:
        - l10n_develop

language: cpp

cache:
    ccache: true
    directories:
        - $HOME/.cache/pip

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    global:
        - PATH=$PATH:$PWD/install/bin
    matrix:
        - RELEASE=
        - RELEASE=true

jobs:
    include:
        - stage: lint
          compiler: clang
          script: .travis/lint.sh
          env: LINT=true  # Travis does not provide ENV var for stage names :(
          addons:
              apt:
                  packages:
                      - qttools5-dev-tools

stages:
    - lint
    - test

matrix:
    exclude:  # OS X builds are slow and limited.
        - os: osx
          compiler: gcc
        - os: osx
          env: RELEASE=

addons:
    apt:
        packages:
            - gcc-4.9
            - g++-4.9
            - libxml2-dev
            - libgoogle-perftools-dev
            - qtbase5-dev
            - qtbase5-dev-tools
            - qttools5-dev
            - qttools5-dev-tools
            - libqt5svg5-dev
            - libqt5opengl5-dev
        sources:
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:kzemek/boost"

before_install:
    - >
      echo "$TRAVIS_COMMIT_MESSAGE"
      | grep -E  '\[(skip travis|travis skip)\]'
      && echo "[skip travis] has been found, exiting."
      && exit 0 || echo "continue"

install:
    - .travis/install.sh  # Dependencies are built with gcc or clang.

before_script:
    - .travis/before_script.sh

script:
    - .travis/script.sh
