sudo: required
dist: trusty

language: cpp

compiler:
    - gcc
    - clang

git:
    depth: 3

env:
    - PATH=$PATH:`pwd`/install/bin
    - PATH=$PATH:`pwd`/install/bin RELEASE=true

before_install:
    - sudo apt-get update -qq

install:
    - ./.travis/install.sh

before_script:
    - mkdir ./install

script:
    - ./.travis/script.sh
