sudo: required
dist: trusty

language: cpp

compiler:
    - gcc
    - clang

git:
    depth: 3

env:
    - PATH=$PATH:`pwd`/install/bin
    - PATH=$PATH:`pwd`/install/bin RELEASE=true

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libboost-program-options-dev
    - sudo apt-get install -qq libboost-filesystem-dev
    - sudo apt-get install -qq libboost-system-dev
    - sudo apt-get install -qq libboost-math-dev
    - sudo apt-get install -qq libxml2-dev
    - sudo apt-get install -qq libxml++2.6-dev
    - sudo apt-get install -qq libgoogle-perftools-dev
    - sudo apt-get install -qq python-lxml
    - sudo apt-get install -qq graphviz
    - sudo apt-get install -qq qt5-default
    - sudo apt-get install -qq doxygen
    - sudo pip install cpp-coveralls
    - sudo pip install nose

before_script:
    - mkdir ./install

script:
    - ./.travis/script.sh
