sudo: false
dist: trusty

branches:
    except:
        - l10n_develop
        - appveyor

language: cpp

cache:
    ccache: true
    directories:
        - $HOME/.cache/pip

os: linux

compiler:
    - gcc
    - clang

env:
    global:
        - PATH=$HOME/.local/bin:$PATH:$PWD/install/bin
        - QT_QPA_FONTDIR=/usr/share/fonts
        - QT_QPA_PLATFORM=offscreen
        - GCC_VERSION=4.9
    matrix:
        - CONFIG=Debug
        - CONFIG=Release

addons:
    apt:
        packages:
            - gcc-4.9
            - g++-4.9
            - libboost-program-options1.58-dev
            - libboost-math1.58-dev
            - libboost-random1.58-dev
            - libboost-filesystem1.58-dev
            - libboost-date-time1.58-dev
            - libxml2-dev
            - libgoogle-perftools-dev
            - qtbase5-dev
            - qtbase5-dev-tools
            - qttools5-dev
            - qttools5-dev-tools
            - libqt5svg5-dev
            - libqt5opengl5-dev
            - fontconfig
            - lcov
        sources: &Sources
            - ubuntu-toolchain-r-test
            - sourceline: "ppa:kzemek/boost"

jobs:
    include:
        - stage: lint
          compiler: clang
          script: .travis/lint.sh
          env: CONFIG=Lint  # Travis does not provide ENV var for stage names :(
          addons:
              apt:
                  packages:
                      - qttools5-dev-tools
        - stage: test
          os: osx  # OS X builds are slow and limited.
          compiler: clang
          env: CONFIG=Release
        - stage: test
          compiler: gcc
          env: CONFIG=Coverage
        - stage: test
          compiler: gcc
          env: CONFIG=Memcheck
          addons:
              apt:
                  packages:
                      - gcc-4.9
                      - g++-4.9
                      - libboost-program-options1.58-dev
                      - libboost-math1.58-dev
                      - libboost-random1.58-dev
                      - libboost-filesystem1.58-dev
                      - libboost-date-time1.58-dev
                      - libxml2-dev
                      - valgrind
                  sources: *Sources
    exclude:
        - compiler: gcc
          env: CONFIG=Debug

stages:
    - lint
    - test

before_install:
    - mkdir -p ~/.local/bin

install:
    - .travis/install.sh  # Dependencies are built with gcc or clang.

before_script:
    - mkdir build install

script:
    - .travis/script.sh
