language: cpp

compiler: gcc

env:
    - PATH=$PATH:`pwd`/install/bin

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libboost-all-dev
    - sudo apt-get install -qq libboost-program-options1.48-dev
    - sudo apt-get install -qq libboost-random1.48-dev
    - sudo apt-get install -qq libboost-filesystem1.48-dev
    - sudo apt-get install -qq libboost-system1.48-dev
    - sudo apt-get install -qq libxml2-dev
    - sudo apt-get install -qq libxml++2.6-dev
    - sudo apt-get install -qq python2.7
    - sudo apt-get install -qq graphviz
    - sudo pip install cpp-coveralls
    - sudo pip install nose

script:
    - mkdir ./install && ./install.py -p --prefix=./install --threads 2 && ./.run_tests.sh

after_success:
    - coveralls  --verbose  --exclude tests  --exclude ./build/CMakeFiles/
      --exclude ./build/lib/  --exclude src/error.h --exclude src/error.cc
      --exclude ./build/bin/  --exclude src/event.h --exclude install/include/
      --exclude src/env.h  --exclude src/reporter.h --exclude src/xml_parser.h
      --exclude src/relax_ng_validator.h
      --exclude src/fault_tree.h
      --exclude src/fault_tree_analysis.h
      --exclude gui/
    - cd ./build && ctest -D Experimental
