language: python
python:
    - 2.7
    - 3.4

git:
    depth: 200

addons:
    apt:
        packages:
            - texlive
            - texlive-fonts-recommended
            - texlive-latex-extra
            - graphviz

install:
    - pip install sphinx sphinx_rtd_theme lizard cppdep
    - wget -q -O - https://sourceforge.net/projects/iscram/files/deps/doxygen-1.8.12.linux.bin.tar.gz | tar xz
    - sudo cp doxygen-1.8.12/bin/* /usr/bin/

before_script:
    - mkdir build

script:
    - cp .travis_cppdep.xml cppdep.xml
    - make build/dep_report.txt scram_core.dot 2> /dev/null
    - make doxygen html linkcheck 2> _warnings.txt
    - cat _warnings.txt && [[ ! -s _warnings.txt ]]
