sudo: required
dist: trusty

language: cpp

cache:
    ccache: true
    directories:
        - $HOME/.cache/pip

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    global:
        - PATH=$PATH:`pwd`/install/bin
        # Intel Parallel Studio
        - secure: "BM1aLsCy0NYk1TCCMeQH6H1O9B+NmZeO6QzRTjy1Xrs8wvoKsuBiazjxSZ6nVWP3F+JtjsOLzeFyELmCf4lobcw8bhzgLZ7ZFaDJl4DC31w+87RdQFYzMe5t53SfflkfBDYkbpbUrt1B7qPk5r0nYDG+QzO3T/XnvSN/0HvmEBQ="
    matrix:
        - RELEASE=
        - RELEASE=true

matrix:
    exclude:
        - os: osx
          compiler: gcc  # GCC is Clang on OS X.
    include:
        - os: linux
          compiler: icc
          env: INTEL_COMPILER=true

addons:
    apt:
        packages:
            - gcc-4.9
            - g++-4.9
            - libxml2-dev
            - libglibmm-2.4-dev
            - libgoogle-perftools-dev
            - qt5-default
        sources:
            - ubuntu-toolchain-r-test

before_install:
    - if [[ -n "${INTEL_COMPILER}" ]]; then export CC=icc; export CXX=icpc; export RELEASE=true; fi

install:
    - .travis/install.sh

before_script:
    - .travis/before_script.sh

script:
    - .travis/script.sh
