clone_depth: 50

platform:
    - x64

configuration:
    # - Debug
    - Release

install:
    - git submodule update --init --recursive
    - set PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
    - pacman --noconfirm -Syu
    - pacman --noconfirm -Syu
    - pacman --noconfirm -S mingw-w64-x86_64-boost
    - pacman --noconfirm -S mingw-w64-x86_64-libxml++2.6
    - pacman --noconfirm -S mingw-w64-x86_64-qt5

before_build:
    - md install
    - md build
    - cd build

build_script:
    - cmake -G "MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=..\install -DCMAKE_BUILD_TYPE=%CONFIGURATION% ..
    - make

after_build:
    - make install
    - cd ..
    - set PATH=%PATH%;%CD%\install\bin

test_script:
    - scram_tests
